- hosts: tag_Name_Master
  gather_facts: False
  roles:
     - role: k8s_master

- hosts: tag_Name_Slave
  gather_facts: False
  roles:
     - role: k8s_slave
   
- hosts: tag_Name_Master
  gather_facts: False
  roles:
     - role: wordpress-mysql
